# Generated by Django 5.2.17 on 2026-09-25 08:42

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_successful_sync_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WeatherPolicyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rain_prob_caution', models.PositiveSmallIntegerField(default=40, help_text='Rain probability caution threshold (%)')),
                ('rain_prob_stop', models.PositiveSmallIntegerField(default=70, help_text='Rain probability stop threshold (%)')),
                ('precip_caution_mm', models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Precipitation caution threshold (mm/h)', max_digits=5)),
                ('precip_stop_mm', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Precipitation stop threshold (mm/h)', max_digits=5)),
                ('gust_caution_kmh', models.DecimalField(decimal_places=2, default=Decimal('25.00'), help_text='Wind gusts caution threshold (km/h)', max_digits=5)),
                ('gust_stop_kmh', models.DecimalField(decimal_places=2, default=Decimal('40.00'), help_text='Wind gusts stop threshold (km/h)', max_digits=5)),
                ('apparent_temp_caution_c', models.DecimalField(decimal_places=2, default=Decimal('30.00'), help_text='Apparent temperature caution threshold (°C)', max_digits=5)),
                ('apparent_temp_stop_c', models.DecimalField(decimal_places=2, default=Decimal('35.00'), help_text='Apparent temperature stop threshold (°C)', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('start_time', models.DateTimeField(help_text='Job start time in UTC instant')),
                ('end_time', models.DateTimeField(help_text='Job end time in UTC instant')),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='core.site')),
                ('policy_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='core.weatherpolicyversion')),
            ],
            options={
                'ordering': ['start_time', 'title'],
            },
        ),
    ]
