# Generated by Django 5.2.17 on 2026-09-25 12:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lagos_date', models.DateField(help_text='Date in Africa/Lagos calendar', unique=True)),
                ('reserved_calls', models.PositiveIntegerField(default=0)),
                ('successful_calls', models.PositiveIntegerField(default=0)),
                ('failed_calls', models.PositiveIntegerField(default=0)),
                ('deferred_calls', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-lagos_date'],
            },
        ),
        migrations.CreateModel(
            name='SiteSyncLease',
            fields=[
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='sync_lease', serialize=False, to='core.site')),
                ('lease_token', models.CharField(max_length=64)),
                ('acquired_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ForecastSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('returned_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('returned_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('returned_elevation', models.FloatField(default=0.0)),
                ('first_retrieved_at', models.DateTimeField(auto_now_add=True)),
                ('hourly_data', models.JSONField(help_text='Normalized hourly forecast values keyed by UTC ISO timestamp')),
                ('coverage_start', models.DateTimeField()),
                ('coverage_end', models.DateTimeField()),
                ('hours_count', models.PositiveIntegerField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='core.site')),
            ],
            options={
                'ordering': ['-first_retrieved_at'],
                'unique_together': {('site', 'content_hash')},
            },
        ),
        migrations.CreateModel(
            name='SyncAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_number', models.PositiveSmallIntegerField(default=1)),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('transient_failure', 'Transient Failure'), ('permanent_failure', 'Permanent Failure'), ('deferred', 'Deferred')], max_length=30)),
                ('failure_category', models.CharField(blank=True, max_length=50)),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_attempts', to='core.site')),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_attempts', to='core.forecastsnapshot')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
