# Generated by Django 5.2.17 on 2026-09-25 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_budgetwindow_sitesynclease_forecastsnapshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_revision', models.PositiveIntegerField()),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('suitable', 'Suitable'), ('caution', 'Caution'), ('unsuitable', 'Unsuitable'), ('unavailable', 'Unavailable')], max_length=20)),
                ('reasons', models.JSONField(default=list, help_text='List of crossed threshold reasons')),
                ('metrics_summary', models.JSONField(default=dict, help_text='Observed maximum metrics')),
                ('evaluated_hours', models.JSONField(default=list, help_text='List of evaluated hour labels in WAT')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='core.job')),
                ('policy_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recommendations', to='core.weatherpolicyversion')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='core.forecastsnapshot')),
            ],
            options={
                'ordering': ['-evaluated_at'],
                'unique_together': {('job', 'job_revision', 'policy_version', 'snapshot')},
            },
        ),
    ]
