# Generated by Django 5.2.17 on 2026-09-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_recommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderCircuitState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('CLOSED', 'Closed (Healthy)'), ('OPEN', 'Open (Cooling Off)'), ('HALF_OPEN', 'Half-Open (Testing Probe)')], default='CLOSED', max_length=20)),
                ('consecutive_transient_failures', models.PositiveSmallIntegerField(default=0)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('cooloff_seconds', models.PositiveIntegerField(default=900)),
                ('last_probe_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
